# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/People-02/Documents/Projeto_Ana/Janela_Loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import time

class Ui_Janela_Loading(object):
    def setupUi(self, Janela_Loading):
        Janela_Loading.setObjectName("Janela_Loading")
        Janela_Loading.resize(640, 480)
        Janela_Loading.setMinimumSize(QtCore.QSize(640, 480))
        Janela_Loading.setMaximumSize(QtCore.QSize(640, 480))
        Janela_Loading.setWindowTitle("")
        Janela_Loading.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Janela_Loading)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(160, 400, 320, 40))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        Janela_Loading.setWindowIcon(QtGui.QIcon(r"D:\Downloads\Diagbot\Logo.png"))
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 300, 191, 60))
        self.label.setStyleSheet("font: 28pt \"OCR A Std\";\n"
"color: rgb(0, 63, 191);\n"
"padding:0px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 30, 320, 260))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(r"D:\Downloads\Diagbot\logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.progressBar.raise_()
        self.label.raise_()
        Janela_Loading.setCentralWidget(self.centralwidget)

        self.retranslateUi(Janela_Loading)
        QtCore.QMetaObject.connectSlotsByName(Janela_Loading)

    def retranslateUi(self, Janela_Loading):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Janela_Loading", "DiagBot"))
        Janela_Loading.setWindowTitle(_translate("Janela_Loading", "DiagBot"))
